version: '3.9'


services:
  db:
    image: bar:latest
    volumes:
      - ./sql/data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    networks:
      - backend-tier

  web:
    image: foo:latest
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=example.com
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=proxy-tier
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=admin@example.com
    networks:
      - proxy-tier
      - backend-tier


networks:
  backend-tier:
  proxy-tier:
    external:
      name: nginx-proxy